"""
Django settings for DashboardDjango project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^c=6k*_(4t%^b-7kykf0lqk0vc+3c$&&hy_o!3_ir+@px)ipcq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
'jazzmin',
    'core',
     'ckeditor',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DashboardDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DashboardDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.getenv("DB_NAME", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.getenv("DB_USER", ""),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", ""),
        "PORT": os.getenv("DB_PORT", ""),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://localhost:3000",
    "https://accoladesintegrated.com",
]


JAZZMIN_SETTINGS = {
    "site_title": "Accolades Integrated Admin",
    "site_header": "Accolades Integrated ",
    "site_brand": "Accolades Integrated ",
    # "site_logo": "/images/image.ico",
    "welcome_sign": "Welcome to Accolades Integrated  Admin",
    "copyright": "Accolades Integrated ",
    "search_model": "projects.Projects",
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "projects.Projects"},
        {"app": "books"},
    ],
    # "usermenu_links": [
    #     {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
    # ],
    # "icons": {
    #     "auth": "fas fa-users-cog",
    #     "auth.user": "fas fa-user",
    #     "auth.Group": "fas fa-users",
    #     "web.Blogs": "fas fa-blog",
    #     "web.BlogsImages": "fas fa-images",
    #     "web.Testimonials": "fas fa-quote-right",
    #     "web.Faq": "fas fa-question-circle",
    #     "web.Galary": "fas fa-images",
    #     "web.GalaryImages": "fas fa-image",
    #     "web.InteriorImages": "fas fa-couch",
    #     "web.Achievements": "fas fa-trophy",
    #     "web.Enquiry": "fas fa-envelope",
    #     "web.CommunityImpact": "fas fa-hand-holding-heart",
    #     "web.SEO": "fas fa-search",
    #     "web.Careers": "fas fa-briefcase",
    #     "web.JobApplication": "fas fa-file-alt",
    #      "projects": "fas fa-building",
    #     "projects.amenities": "fas fa-concierge-bell",
    #     "projects.bank": "fas fa-university",
    #     "projects.projects": "fas fa-project-diagram",
    #     "projects.projectimages": "fas fa-images",
    #     "projects.projectfeatures": "fas fa-star",
    #     "projects.projectamenitiesimages": "fas fa-image",
    #     "projects.projectspecification": "fas fa-info-circle",
    #     "projects.projectplan": "fas fa-map",
    #     "projects.projectvideos": "fas fa-video",
    #     "projects.projectnearby": "fas fa-map-marker-alt",
    #     "projects.currentstatus": "fas fa-calendar-check",
    # },
    "related_modal_active": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "custom_css": "css/custom_admin.css",
    "custom_js": None,
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    "custom_links": {"books": [{"name": "Make Messages", "url": "make_messages", "icon": "fas fa-comments", "permissions": ["books.view_book"]}]},
    "language_chooser": False,
    "theme": "default",
    "dark_mode_theme": "dark",
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
}